spring:
  application:
    name: gateway-server

server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

