spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: uiservice
#            allowedMethods: "*"
#            allowCredentials: true
#            maxAge: 7200
#            allowedHeaders: "*"
#            exposedHeaders:
#              - "Access-Control-Allow-Origin"
#              - "Access-Control-Allow-Methods"
#              - "Access-Control-Max-Age"
#              - "Access-Control-Allow-Headers"
#              - "Cache-Control"
#              - "Authorization"
#              - "Content-Type"
#        routes:
#          - id: group_management_service_route
#            uri: http://group-management-service
#            predicates:
#              - Path=/group/*

#    kubernetes:
#      discovery:
#        filter: "metadata.labels['s1p']"


server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

