---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spring-cloud-kubernetes-discoveryserver
  name: spring-cloud-kubernetes-discoveryserver:view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: gateway-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
